# -*- coding: utf-8 -*-
"""Lab2_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctk994H0IHM8zS8RTR6EYjLe1p2mWSVG
"""

import pandas as pd
housing= pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/20240319120216/housing.csv")
housing.info()

housing.describe()

import matplotlib.pyplot as plt

housing.hist(bins=10, figsize=(20,15))
plt.show()

from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(
    housing, test_size=0.2, random_state=42
)
housing["income_cat"] = pd.cut(
    housing["median_income"],
    bins=[0., 1.5, 3.0, 4.5, 6., float("inf")],
    labels=[1, 2, 3, 4, 5]
)

from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_idx, test_idx in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_idx]
    strat_test_set = housing.loc[test_idx]

housing.plot(
    kind="scatter",
    x="longitude",
    y="latitude",
    alpha=0.4,
    s=housing["population"]/100,
    label="Population",
    figsize=(10,7),
    c="median_house_value",
    cmap="jet",
    colorbar=True
)
plt.legend()
plt.show()

corr_matrix = housing.corr(numeric_only=True)
corr_matrix["median_house_value"].sort_values(ascending=False)
housing.plot(
    kind="scatter",
    x="median_income",
    y="median_house_value",
    alpha=0.1
)
plt.show()

housing["rooms_per_household"] = (
    housing["total_rooms"] / housing["households"]
)

housing["bedrooms_per_room"] = (
    housing["total_bedrooms"] / housing["total_rooms"]
)

housing["population_per_household"] = (
    housing["population"] / housing["households"]
)
housing.corr(numeric_only=True)["median_house_value"].sort_values(ascending=False)

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

housing_num = housing.drop("ocean_proximity", axis=1)
imputer.fit(housing_num)

housing_num_imputed = pd.DataFrame(
    imputer.transform(housing_num),
    columns=housing_num.columns
)

housing_cat = housing[["ocean_proximity"]]

housing_encoded = pd.get_dummies(housing_cat)
housing_encoded.head()

