# -*- coding: utf-8 -*-
"""labexam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1232jMkwosDecgRzwmgIby_5dafZgdkyL
"""

import pandas as pd

df=pd.read_csv("/content/ball_by_ball_ipl_data.csv")

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

df = df[~df['batsman_run'].isin([3, 5])]

# Convert to better target (3-class problem)
def categorize_runs(x):
    if x == 0:
        return 0   # dot ball
    elif x in [1, 2]:
        return 1   # running
    else:
        return 2   # boundary (4,6)

df['run_class'] = df['batsman_run'].apply(categorize_runs)

df = df[[
    'batter_name',
    'bowler_name',
    'non_striker_name',
    'batting_team',
    'bowling_team',
    'run_class'
]]

le = LabelEncoder()

for col in ['batter_name', 'bowler_name', 'non_striker_name', 'batting_team', 'bowling_team']:
    df[col] = le.fit_transform(df[col])

X = df.drop('run_class', axis=1)
y = df['run_class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced_subsample',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("=== Random Forest ===")
print("Accuracy:", accuracy_score(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

print("ADABoost")
print("Accuracy:", accuracy_score(y_test, xgb_pred))
print(classification_report(y_test, xgb_pred))